#!/usr/bin/env bash
# Runs on the freshly-provisioned Azure VM. Brings up the full FuelBorn host:
#   - Mount data disk at /srv/pods
#   - Install Docker, move /var/lib/docker to data disk
#   - Install Pelican Panel via docker compose
#   - Install Wings binary + systemd unit (config.yml supplied later from panel)
#   - Install Node.js (for the Next.js frontend, brought up via separate script)
#
# Required env (export before running, or supply via /etc/pods-ml.env):
#   APP_URL          e.g. https://pods-ml-prototype.eastus.cloudapp.azure.com
#   LE_EMAIL         email for Let's Encrypt
#
# Optional:
#   MYSQL_ROOT_PASSWORD, MYSQL_PASSWORD — autogenerated if unset
set -euo pipefail

# ---- load env from /etc/pods-ml.env if present ------------------------------
if [[ -f /etc/pods-ml.env ]]; then
  set -a; . /etc/pods-ml.env; set +a
fi
: "${APP_URL:?Set APP_URL (e.g. https://pods-ml-prototype.eastus.cloudapp.azure.com)}"
: "${LE_EMAIL:?Set LE_EMAIL}"

MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-$(openssl rand -hex 24)}"
MYSQL_PASSWORD="${MYSQL_PASSWORD:-$(openssl rand -hex 24)}"

echo "==> 1/7 Mounting data disk at /srv/pods"
DATA_DEV=$(lsblk -dno NAME,SIZE | awk '$2=="128G"{print "/dev/"$1; exit}')
if [[ -z "${DATA_DEV:-}" ]]; then
  echo "No 128 GB unmounted disk found — assuming /srv/pods already exists" >&2
else
  if ! blkid "$DATA_DEV" >/dev/null 2>&1; then
    sudo mkfs.ext4 -F -L pods-data "$DATA_DEV"
  fi
  sudo mkdir -p /srv/pods
  if ! mount | grep -q "on /srv/pods"; then
    sudo mount "$DATA_DEV" /srv/pods
    UUID=$(blkid -s UUID -o value "$DATA_DEV")
    if ! grep -q "$UUID" /etc/fstab; then
      echo "UUID=$UUID  /srv/pods  ext4  defaults,nofail  0 2" | sudo tee -a /etc/fstab
    fi
  fi
fi
sudo mkdir -p /srv/pods/{docker,pelican,pelican/data,pelican/db,pelican/logs}

echo "==> 2/7 Installing Docker"
if ! command -v docker >/dev/null; then
  curl -fsSL https://get.docker.com | sudo sh
  sudo systemctl enable --now docker
fi

echo "==> 3/7 Pointing docker data-root at /srv/pods/docker"
if ! grep -q '"data-root"' /etc/docker/daemon.json 2>/dev/null; then
  echo '{"data-root": "/srv/pods/docker"}' | sudo tee /etc/docker/daemon.json
  sudo systemctl restart docker
fi

echo "==> 4/7 Writing Pelican compose + env"
sudo mkdir -p /srv/pods/pelican
sudo tee /srv/pods/pelican/.env >/dev/null <<EOF
APP_URL=$APP_URL
LE_EMAIL=$LE_EMAIL
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
MYSQL_PASSWORD=$MYSQL_PASSWORD
EOF
sudo chmod 600 /srv/pods/pelican/.env
sudo cp "$(dirname "$0")/../pelican/compose.yml" /srv/pods/pelican/compose.yml

echo "==> 5/7 Bringing up Pelican Panel"
( cd /srv/pods/pelican && sudo docker compose --env-file .env up -d )

echo "    Waiting for panel to come online (up to 3 min)..."
for i in $(seq 1 36); do
  if curl -ksf "https://localhost/" -o /dev/null; then
    echo "    Panel is up."
    break
  fi
  sleep 5
done

echo "==> 6/7 Installing Wings binary + systemd unit"
sudo mkdir -p /etc/pelican /var/run/wings
if [[ ! -x /usr/local/bin/wings ]]; then
  ARCH=$([[ "$(uname -m)" == "x86_64" ]] && echo amd64 || echo arm64)
  sudo curl -L -o /usr/local/bin/wings \
    "https://github.com/pelican-dev/wings/releases/latest/download/wings_linux_$ARCH"
  sudo chmod +x /usr/local/bin/wings
fi
sudo cp "$(dirname "$0")/../wings/wings.service" /etc/systemd/system/wings.service
sudo systemctl daemon-reload
# don't enable yet — config.yml hasn't been generated by the panel

echo "==> 7/7 Installing Node.js 20 LTS (for Next.js frontend)"
if ! command -v node >/dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  sudo apt-get install -y nodejs
  sudo npm i -g pnpm
fi

echo
echo "============================================================"
echo "BOOTSTRAP COMPLETE"
echo "============================================================"
echo "Panel URL  : $APP_URL"
echo "Next steps :"
echo "  1. Create admin user:"
echo "     sudo docker compose -f /srv/pods/pelican/compose.yml exec panel php artisan p:user:make"
echo "  2. Log in at $APP_URL, create a Node, copy its config.yml to /etc/pelican/config.yml"
echo "  3. sudo systemctl enable --now wings"
echo "  4. Import eggs/hermes-agent.json via panel UI"
echo "  5. Generate an Application API key (admin → API) and put it in /srv/pods/frontend/.env"
echo "  6. cd /srv/pods/frontend && pnpm install && pnpm build && sudo systemctl enable --now pods-ml-frontend"
echo "============================================================"
echo "DB passwords saved to /srv/pods/pelican/.env (mode 600)."
